### ISSUE TITLE
Deprecate MapCenter Classic

### ISSUE THREAD

**Issue by stupiddingo** [idahofishgame/huntplanner_mapcenter#2]
It is time to retire the Huntplanner Mapcenter Classic.  
## October Sessions

Mapcenter Classic: 27 sessions
Mapcenter: 39.4k sessions
## Unique Pageviews Oct. 1, 2014 - Feb 1, 2015

Mapcenter Classic: 66
Mapcenter: 68,924
## TODO
- [x] Remove references to Mapcenter classic in help documention
- [x] Zip up mapcenter classic, leave in archive folder _bt_
- [x] Post basic page explaining old version is no longer accessible _bt_
- [x] Remove antiquated map service _bt_

This issue may be closed when all items are completed.

**Comment by pbond-idfg** [comment]
Mapcenter classic reference removed.

**Comment by stupiddingo** [comment]
Removed old map service.
